version: '0.1'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 manage:app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=microhms
      - POSTGRES_PASSWORD=microhms
      - POSTGRES_DB=microhms

volumes:
  postgres_data:
