"""empty message

Revision ID: 95dfbf0bec9c
Revises: 95d4ee921d6a
Create Date: 2022-04-09 23:15:09.619546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95dfbf0bec9c'
down_revision = '95d4ee921d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config', 'hsnsac')
    op.drop_column('config', 'pan')
    op.drop_column('config', 'gstin')
    op.drop_column('config', 'acs')
    op.drop_column('invoice_headers', 'gstin')
    op.drop_column('invoice_headers', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_headers', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('invoice_headers', sa.Column('gstin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('config', sa.Column('acs', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('config', sa.Column('gstin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('config', sa.Column('pan', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('config', sa.Column('hsnsac', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
